### ISSUE TITLE
Support node 10

### ISSUE THREAD

**Issue by QuentinFarizonAfrimarket** [Botfuel/botfuel-dialog#268]
**Is your feature request related to a problem? Please describe.**
It's not possible to run Botfuel with node 10, message is :
error botfuel-dialog@12.1.0: The engine "node" is incompatible with this module. Expected version "8.x". Got "10.15.3"

**Describe the solution you'd like**
I think this project must be already compatible with node 9/10/11, you should just update your "engine" section in package.json to reflect this

**Comment by KevinDepuydt** [comment]
The issue should be fixed in the version **botfuel-dialog@12.3.0**
